# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    purchase_fee: 0.01
    sales_credit: 0.01
    exchange_rates:
        EUR_GBP: 1.5678
        GBP_EUR: 1.5432

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            float $purchaseFee: '%purchase_fee%'
            float $salesCredit: '%sales_credit%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Application\Infrastructure\Repositories\ExchangeRateRepository:
        arguments:
            $exchangeRates: '%exchange_rates%'

    App\Application\Commands\ExchangeMoneyCommand:
        arguments:
            $exchangeService: '@App\Application\Services\ExchangeService'
        tags:
            - { name: 'console.command' }
